### ISSUE TITLE
리마인드 알람이 `한 번`만 울리고 다음 날부터 울리지 않는 Bug

### ISSUE THREAD

**Issue by 60jong** [Todoary/Todoary-Server#260]
원래 요구사항이 그랬는지 모르겠는데 (아닌 것으로 알고 있습니다.) 리마인드 알람이 마지막 일기 작성 후 7일이 지난 후에 `한 번`만 울릴 뿐이라 매일 울리도록 수정할 필요가 있어 보입니다.

맞을까요...?
@Todoary/todoary_serverdeveloper 
@yooyeri

**Comment by melonturtle** [comment]
리마인드 알림은 원래 7일로 알고있습니다. 오래 일기 작성을 안했을때 리마인드를 하는 목적이라서 아마 그럴거에요. 어플에서 알림 옆에 ? 눌러보시면 일주일동안 안썼을때라고 메시지도 뜹니다!

데일리 알림 → 하루기록 알림이 매일 오구요.

**Comment by melonturtle** [comment]
그래서 버그가 아닙니다~~

**Comment by 60jong** [comment]
아 그렇군요~~
