### ISSUE TITLE
데일리 알람이 울리지 않는 Bug

### ISSUE THREAD

**Issue by 60jong** [Todoary/Todoary-Server#261]
(다들 데일리 알람 잘 오고 계신가요??)

데일리 알람이 오지 않고 있습니다. 버그 수정이 필요해 보입니다.
@Todoary/todoary_serverdeveloper

**Comment by goldggyul** [comment]
전 방금 투두 새로 생성했는데 알림 잘왔습니다! DB에 본인 계정에 FCM 토큰값 확인해보셨나요? 아님 이상이 없으면 알림 허용을 안했을수도 있구요.. 제 친구가 알림 안온다해서 확인했었는데 친구는 알림을 꺼놔서 안온거였습니다

**Comment by melonturtle** [comment]
아 투두가 아니고 데일리 알림이군요 그러고보니 안온것같기도 하네요..

**Comment by 60jong** [comment]
시간 날 때 바로 수정해보겠습니다

**Comment by melonturtle** [comment]
@60jong 

이거 코드로 고친건 아니고 원인 찾았는데 일단 지금 알림을 보내볼 순 없어서 오늘 밤에 봐야할 것 같습니다. 일단 핵심만 말하면 JPA 관련 오류인 것 같습니다. 아래에 설명할게요!

## 발생 원인

일단 투두 알림은 잘 오고있어서 데일리 알림만 안오는 건 FCM문제는 아닌거 같았고.. 스케쥴링 문제도 아닌 것 같았습니다. 게다가 제 기억엔 분명 예전에 데일리 알림이 왔거든요.. 맞나요?

암튼 로그파일을 살펴보니까 Daily alarm triggered 메시지는 나오고 있어서 스케쥴링 문제는 아닌 건 확실했습니다
```
2023-03-29 00:00:02.549 INFO  c.t.m.s.w.c.AlarmController - Daily alarm triggered
2023-03-29 00:00:03.821 ERROR LoggingAspectHandler - [Exception] AlarmController.pushDailyAlarm() | message=More than one row with the given identifier was found: {특정 멤버 아이디}, for class: com.todoary.ms.src.domain.token.RefreshToken; nested exception is org.hibernate.HibernateException: More than one row with the given identifier was found: 194, for class: com.todoary.ms.src.domain.token.RefreshToken
```

그 아래 메시지를 보고 db를 보니까 RefreshToken 테이블에 저기 특정 멤버 아이디만 리프레쉬 토큰이 두개 있더라구요. 
```sql
select member_id, count(member_id)
FROM refresh_token
GROUP BY member_id;
```
데일리 알람을 보낼때 멤버를 지금 전체 조회해서 반환하고 있는데, 그때 한 멤버가 refresh token이 두개라서 OneToOne인 연관관계와 맞지 않아서 오류가 난 것 같습니다.

그래서 투두 알림은 문제없이 보내졌던 이유는 리프레쉬 토큰이 두개인 멤버가 아닌 다른 멤버에게만 보내고 있었어서 문제가 없던 것 같아요.

리프레쉬 토큰 두개는 생성시간이 ms 정도만 차이났구요. 소셜 계정인데, 아마 예전에 회원가입 연속으로 되는 오류때문에 계정 여러개 남아있던게 겹친 것 같기도 하구요. 리프레쉬 토큰 변경하는 로직을 지금 봤을때는 두개 생길 이유는 없는데.. 그래서 가입이 연속으로 돼서 save를 두번한건가 싶습니다. 

암튼 일단 하나는 삭제해서 refresh token 테이블에 멤버 id가 여러개인건 없구요. 아마 오늘 밤부턴 데일리 알림이 잘 오지 않을까 생각합니다.. 😭

## 제안 사항

그리고 일단 원인을 알았지만, refresh token과 상관 없는 알림을 보내는건데 refresh token때문에 문제가 났던 거라 더 찾기 힘들어지는 것 같아요. 데일리 알림을 보낼 때는 사실 투두같이 내용도 필요없고 그냥 fcm 토큰만 있으면 되니까 fcm 토큰만 받아오는 게 좋을 수 있을 것 같습니다. 어떻게 생각하세요?

**Comment by melonturtle** [comment]
오옹 방금 데일리 알림은 일단 잘 왔네요 정답~!

**Comment by melonturtle** [comment]
문제 확인됐으니 refresh token 테이블에 유니크 걸었습니다~ 이슈 닫겠습니다.

```sql
ALTER TABLE refresh_token MODIFY COLUMN member_id BIGINT UNIQUE;
```

**Comment by 60jong** [comment]
@goldggyul
오 고생했습니다!!

중복 회원가입이 계속 문제였군요... 일단 unique처리하는게 맞는 것 같습니다!!
